version: '3.7'

services:

  redis:
    image: redis:latest
    container_name: cache
    ports: 
      - 6379:6379
    volumes:
        - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis

  app:
    build: ./
    volumes:
      - ./:/var/www/app
      - /home:/mnt
    ports:
      - 3000:3000
    links: 
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
      - TMDB_KEY=<your api key>
    command:
      sh -c 'npm i && npm run dev'

volumes:
  redis-data: